paths:
  drivers_andor: src/dlab/hardware/drivers/andor_driver
  drivers_avaspec: src/dlab/hardware/drivers/avaspec_driver
  drivers_slm: src/dlab/hardware/drivers/SLM_driver
  ressources: ressources
  logs_dir: logs
  data_dir: C:/data
runtime:
  pressure_update_interval_s: 5.0
  log_level: INFO
devices:
  pressure: false
stages:
  default_ids:
    0: '83837714'
    1: '00000000'
    2: '00000000'
    3: '00000000'
    4: '00000000'
    5: '83837725'
    6: '00000000'
    7: '00000000'
    8: '00000000'
zaber:
  port: COM4
  baud: 9600
  range:
    min: 24.0
    max: 25.3
waveplates:
  calibration_files:
    '1': calibration/wp1/default_wp1.txt
    '2': calibration/wp2/default_wp2.txt
    '3': calibration/wp3/default_wp3.txt
    '4': calibration/wp4/default_wp4.txt
    '5': calibration/wp5/default_wp5.txt
    '6': calibration/wp6/default_wp6.txt
slm:
  beam_radius_on_slm: 0.0035
  defaults_file: ressources/saved_settings/slm_defaults.yaml
  red_default: ressources/saved_settings/SLM_red/red_default_settings.txt
  green_default: ressources/saved_settings/SLM_green/green_default_settings.txt
avaspec:
  calibration_file: ressources/calibration/avaspec/avaspec_calibration_1030nm.dat
ports:
  pfeiffer: COM9
metrics:
  prometheus_port: 8000
  grafana_url: http://localhost:3000/goto/FsiuGkbHg?orgId=1
crosshair:
  daheng_1:
    x_mm: 2.50514254723088
    y_mm: 2.8337411632219167
  daheng_2:
    x_mm: 2.576213086981695
    y_mm: 2.103298574425944
andor:
  crosshair:
    x: 114.56372885154052
    y: 144.92521008403355
